/*
 * Copyright (c) 2019. Xiaolong Xu, ZhejiangLab.
 * Email: xuxiaolong@zhejianglab.com
 * Date: 2020.01.16
 * Note:
 */

package config

import "time"

// packet
const (
	PAYLOAD_LEN_MASK = 0x7FFFFFFF

	SIZE_FIELD_SIZE = 4
	PREPAYLOAD_SIZE = SIZE_FIELD_SIZE
	MAX_PACKET_SIZE = 16 * 1024 * 1024
	MAX_PAYLOAD_SIZE = MAX_PACKET_SIZE - SIZE_FIELD_SIZE
)

// connection
const (
	CLIENT_PROXY_WRITE_FLUSH_INTERVAL = time.Millisecond * 5
	UDP_CLIENT_PROXY_WRITE_FLUSH_INTERVAL = time.Millisecond * 5
	SERVER_PROXY_WRITE_FLUSH_INTERVAL = time.Millisecond * 5
	UDP_SERVER_PROXY_WRITE_FLUSH_INTERVAL = time.Millisecond * 5

	CLIENT_PROXY_WRITE_BUFFER_SIZE = 1024 * 1024
	CLIENT_PROXY_READ_BUFFER_SIZE = 1024 * 1024
	CLIENT_PROXY_SET_NO_DELAY = true
	UDP_CLIENT_PROXY_WRITE_BUFFER_SIZE = 1024 * 1024
	UDP_CLIENT_PROXY_READ_BUFFER_SIZE = 1024 * 1024

	SERVER_PROXY_WRITE_BUFFER_SIZE = 64 * 1024
	SERVER_PROXY_READ_BUFFER_SIZE = 64 * 1024
	SERVER_PROXY_SET_NO_DELAY = true
	UDP_SERVER_PROXY_WRITE_BUFFER_SIZE = 64 * 1024
	UDP_SERVER_PROXY_READ_BUFFER_SIZE = 64 * 1024

)

// networking serve
const (
	RESTART_TCP_SERVER_INTERVAL = 3 * time.Second
	RESTART_UDP_SERVER_INTERVAL = 3 * time.Second
)